name: kuncie_flutter_test
description: "A new Flutter project."
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  google_fonts: ^4.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.3.2
  dart_code_metrics: ^5.3.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.5.4
  mocktail: ^1.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
